services:
  db:
    container_name: postgresForAddressProject
    image: postgres:15.2
    environment:
      POSTGRES_DB: databaseForAddress
      POSTGRES_USER: armin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: